### ISSUE TITLE
Consider rename this repo name to `wasi-config`

### ISSUE THREAD

**Issue by Mossaka** [WebAssembly/wasi-config#17]
The `runtime` name is dropped from all interfaces. See https://github.com/WebAssembly/wasi-runtime-config/pull/14#issuecomment-2344107573

**Comment by thomastaylor312** [comment]
Making sure this is here publicly, I'm in agreement with this change.

**Comment by ricochet** [comment]
After the last WASI SG, we had agreement to rename. Rename complete!
